baseurl = "https://ianms17.github.io"
title = "Ian's Personal Site"
theme = "hugo-coder"
languagecode = "en-us"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[markup.highlight]
style = "monokai"

[params]
  author = "Ian Stephenson"
  info = "Cloud Platform and Automation Engineer"
  description = "Ian Stephenson's Personal Site"
  keywords = "blog,developer,personal"
  avatarurl = "images/gpt_bears_avatar.png"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "GitHub"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/ianms17/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/ian-stephenson/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"